version: "3.8"
services:
  creditmarket-redis:
    container_name: creditmarket-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: ryusunny/creditmarket-redis
    ports:
      - "6379:6379"
  creditmarket-db:
    container_name: creditmarket-db
    build:
      dockerfile: Dockerfile
      context: ./database
    image: ryusunny/creditmarket-db
    environment:
      MYSQL_DATABASE: 'creditmarket'
      MYSQL_ROOT_PASSWORD: 'fbtjs4956'
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3308:3308"
