version: "3.8"
services:
  creditmarket-redis: # 서비스명
    container_name: creditmarket-redis # 컨테이너명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: ryusunny/creditmarket-redis
    ports:
      - "6379:6379"

  creditmarket-db: # 서비스명
    container_name: creditmarket-db # 컨테이너명
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./database
    image: ryusunny/creditmarket-db
    environment:
      MYSQL_DATABASE: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  creditmarket-app: # 서비스명
    container_name: creditmarket-app # 컨테이너명
    build: .
    depends_on: # DB, REDIS 컨테이너가 실행된 다음 WEB을 실행시킨다.
      - creditmarket-db
      - creditmarket-redis
    image: ryusunny/creditmarket-app
    environment:
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "80:8080" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    restart: always
    # depends on은 실행 순서만 컨트롤 할뿐,
    # 컨테이너 안의 서비스가 실행가능한 상태인지까지는 확인 하지 않기 때문에
    # DB 또는 Redis가 아직 실행가능한 상태가 아니여서 실패하는 경우 재시작 하도록 설정
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
