version: "3.8"
services:
  creditmarket-redis:
    container_name: creditmarket-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: ryusunny/creditmarket-redis
    ports:
      - "6379:6379"
  creditmarket-db:
    container_name: creditmarket-db
    build:
      dockerfile: Dockerfile
      context: ./database
    image: ryusunny/creditmarket-db
    environment:
      MYSQL_DATABASE: 'creditmarket'
      MYSQL_ROOT_PASSWORD: 'fbtjs4956'
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3307:3306"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

