spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB #
  kafka:
    consumer:
      group-id: alarm

open:
  api:
    key: b6ce706b7c9aba76289b5403f47eafb1

jwt:
  token:
    secret: secretKey

file:
  dir: C:/project/

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/creditmarket
    username: root
    password: fbtjs4956
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://creditmarket-db:3306/creditmarket
    username: root
    password: fbtjs4956
  redis:
    host: creditmarket-redis
    port: 6379
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true




