spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

open:
  api:
    key: b6ce706b7c9aba76289b5403f47eafb1

jwt:
  token:
    secret: secretKey

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/creditmarket
    username: root
    password: fbtjs4956
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://creditmarket-db:3308/creditmarket
    username: root
    password: fbtjs4956
  redis:
    host: creditmarket-redis
    port: 6379
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true



